# Generated by Django 4.0.1 on 2022-04-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done_at',
            field=models.DateTimeField(null=True),
        ),
    ]
